version: 2
project_name: locom

release:
  github:
    owner: localcompose
    name: locom

homebrew_casks:
  - name: locom
    repository:
      owner: localcompose
      name: homebrew-locom
    homepage: "https://github.com/localcompose"
    description: "A command-line tool to help manage local Docker Compose stacks in a clean, self-hosted, offline-friendly way"

builds:
  - main: ./cmd/locom
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm
    ldflags: "-s -w -X main.Name={{.ProjectName}} -X main.Version={{.Version}}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
