project_name: locom

release:
  github:
    owner: localcompose
    name: locom

brews:
  - name: locom
    repository:
      owner: localcompose
      name: homebrew-locom
    homepage: "https://github.com/localcompose/locom"
    description: "Local-only Docker Compose stack manager"
    test: |
      locom help

builds:
  - main: ./main.go
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ldflags: "-s -w -X main.Name={{.ProjectName}} -X main.Version={{.Version}}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{.Version}}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
